"""Filesystem JSON artifact store for native content slimming.

The store is deliberately small and dependency-free: each artifact is one JSON
file under the active Hermes profile. Writes are temp-file + fsync + atomic
rename, then read back and hash verified before the caller can emit a marker.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping

from hermes_constants import get_hermes_home

SCHEMA_VERSION = 1
DEFAULT_RAW_SOURCE = "tool-result-returned"
_DEFAULT_TOOL_STATUS = "success"
_SAFE_COMPONENT_RE = re.compile(r"[^A-Za-z0-9_.-]+")
_ARTIFACT_ID_RE = re.compile(r"^art_[A-Za-z0-9_.-]+$")


class ArtifactStoreError(RuntimeError):
    """Base class for artifact-store failures."""


class ArtifactNotFoundError(ArtifactStoreError):
    """Raised when an artifact id has no artifact file or tombstone."""


class ArtifactGoneError(ArtifactStoreError):
    """Raised when an artifact was garbage-collected and only a tombstone remains."""

    def __init__(self, artifact_id: str, tombstone: Mapping[str, Any]):
        self.artifact_id = artifact_id
        self.tombstone = dict(tombstone)
        super().__init__(f"artifact gone: {artifact_id}")


class ArtifactIntegrityError(ArtifactStoreError):
    """Raised when a stored artifact fails schema/hash verification."""


def utc_now_iso() -> str:
    """Return a compact UTC ISO-8601 timestamp with a Z suffix."""

    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def parse_utc_iso(value: Any) -> datetime | None:
    """Parse an ISO timestamp generated by this module, returning UTC."""

    if not value:
        return None
    text = str(value).strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def sha256_text(text: str) -> str:
    """Return sha256 over the exact UTF-8 bytes of ``text``."""

    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def raw_byte_len(text: str) -> int:
    return len(text.encode("utf-8"))


def safe_component(value: Any, *, fallback: str = "none", max_len: int = 96) -> str:
    """Make a session/tool id safe for a single path component."""

    text = str(value or "").strip() or fallback
    text = _SAFE_COMPONENT_RE.sub("_", text).strip("._-") or fallback
    return text[:max_len]


def default_artifact_root() -> Path:
    """Profile-local artifact root for the active Hermes profile."""

    return get_hermes_home() / "compression" / "artifacts"


def build_artifact_id(session_id: str, tool_call_id: str, raw_text: str) -> str:
    """Build the deterministic v0.1 artifact id for a tool result."""

    digest = sha256_text(raw_text)
    return (
        f"art_{safe_component(session_id, fallback='session')}_"
        f"{safe_component(tool_call_id, fallback='tool_call')}_{digest[:8]}"
    )


def validate_artifact_id(artifact_id: str) -> str:
    """Validate an artifact id before turning it into a filesystem path."""

    text = str(artifact_id or "")
    if not _ARTIFACT_ID_RE.fullmatch(text) or ".." in text:
        raise ArtifactNotFoundError(f"invalid artifact id: {artifact_id!r}")
    return text


def _fsync_dir(path: Path) -> None:
    """Best-effort fsync of a directory after rename/unlink operations."""

    try:
        fd = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def atomic_write_json_file(path: Path, payload: Mapping[str, Any], *, mode: int = 0o600) -> None:
    """Write JSON via temp file, fsync, and atomic rename.

    The temp file lives in the destination directory. It is removed on failure
    before the atomic rename. Parent-directory fsync is best-effort because some
    platforms/filesystems reject directory fsync.
    """

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_name(f"{path.name}.tmp.{os.getpid()}.{uuid.uuid4().hex}")
    encoded = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    fd: int | None = None
    try:
        fd = os.open(str(tmp_path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            fd = None  # ownership transferred to handle
            handle.write(encoded)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(str(tmp_path), str(path))
        try:
            os.chmod(path, mode)
        except OSError:
            pass
        _fsync_dir(path.parent)
    except Exception:
        if fd is not None:
            try:
                os.close(fd)
            except OSError:
                pass
        try:
            tmp_path.unlink()
        except FileNotFoundError:
            pass
        raise


class ArtifactStore:
    """Filesystem-JSON artifact store rooted in one Hermes profile."""

    def __init__(self, root: str | Path | None = None):
        self.root = Path(root) if root is not None else default_artifact_root()

    def session_dir(self, session_id: str) -> Path:
        return self.root / safe_component(session_id, fallback="session")

    def path_for(self, artifact_id: str, *, session_id: str) -> Path:
        return self.session_dir(session_id) / f"{validate_artifact_id(artifact_id)}.json"

    def tombstone_path_for(self, artifact_id: str, *, session_id: str) -> Path:
        return self.session_dir(session_id) / f"{validate_artifact_id(artifact_id)}.gone.json"

    def artifact_file_size(self, artifact_id: str, *, session_id: str) -> int:
        return self.path_for(artifact_id, session_id=session_id).stat().st_size

    def iter_artifact_paths(self) -> Iterable[Path]:
        if not self.root.exists() or not self.root.is_dir():
            return []
        return sorted(
            path
            for path in self.root.glob("*/*.json")
            if not path.name.endswith(".gone.json")
            and not path.name.startswith(".gc_status")
            and ".tmp." not in path.name
        )

    def iter_tombstone_paths(self) -> Iterable[Path]:
        if not self.root.exists() or not self.root.is_dir():
            return []
        return sorted(self.root.glob("*/*.gone.json"))

    def find_artifact_path(self, artifact_id: str, *, session_id: str | None = None) -> Path:
        artifact_id = validate_artifact_id(artifact_id)
        if session_id is not None:
            path = self.path_for(artifact_id, session_id=session_id)
            if path.exists():
                return path
            tombstone = self.tombstone_path_for(artifact_id, session_id=session_id)
            if tombstone.exists():
                raise ArtifactGoneError(artifact_id, _read_json_dict(tombstone))
            raise ArtifactNotFoundError(f"artifact not found: {artifact_id}")

        matches = sorted(self.root.glob(f"*/{artifact_id}.json")) if self.root.exists() else []
        if matches:
            return matches[0]
        tombstones = sorted(self.root.glob(f"*/{artifact_id}.gone.json")) if self.root.exists() else []
        if tombstones:
            raise ArtifactGoneError(artifact_id, _read_json_dict(tombstones[0]))
        raise ArtifactNotFoundError(f"artifact not found: {artifact_id}")

    def read_record(self, artifact_id: str, *, session_id: str | None = None) -> dict[str, Any]:
        path = self.find_artifact_path(artifact_id, session_id=session_id)
        data = _read_json_dict(path)
        self._verify_record(data, expected_artifact_id=artifact_id)
        return data

    def write_artifact(
        self,
        *,
        session_id: str,
        tool_call_id: str,
        raw_text: str,
        artifact_id: str | None = None,
        task_id: str | None = None,
        turn_id: str | None = None,
        api_request_id: str | None = None,
        tool_name: str | None = None,
        tool_status: str = _DEFAULT_TOOL_STATUS,
        created_at: str | None = None,
        raw_source: str = DEFAULT_RAW_SOURCE,
        preview_strategy: str = "none",
        preview_bytes: int = 0,
        omitted_bytes: int = 0,
        lossy: bool = False,
        classification_reason: str = "",
        redaction_applied: bool = False,
        metadata: Mapping[str, Any] | None = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Persist one immutable artifact and verify it by reading it back.

        If the deterministic id already exists with the same hash, the existing
        verified record is returned unchanged. If the same id exists with a
        different hash, a numeric suffix is appended rather than overwriting.
        """

        if not isinstance(raw_text, str):
            raw_text = "" if raw_text is None else str(raw_text)
        session_id = str(session_id or "")
        tool_call_id = str(tool_call_id or "")
        digest = sha256_text(raw_text)
        base_artifact_id = artifact_id or build_artifact_id(session_id, tool_call_id, raw_text)
        candidate_id = base_artifact_id
        counter = 0
        while True:
            path = self.path_for(candidate_id, session_id=session_id)
            tombstone = self.tombstone_path_for(candidate_id, session_id=session_id)
            if path.exists():
                try:
                    existing = self.read_record(candidate_id, session_id=session_id)
                except ArtifactStoreError:
                    existing = None
                if existing and existing.get("raw_sha256") == digest:
                    return existing
                counter += 1
                candidate_id = f"{base_artifact_id}_{counter}"
                continue
            if tombstone.exists():
                counter += 1
                candidate_id = f"{base_artifact_id}_{counter}"
                continue
            break

        record: dict[str, Any] = {
            "schema_version": SCHEMA_VERSION,
            "artifact_id": candidate_id,
            "session_id": session_id,
            "task_id": task_id or "",
            "turn_id": turn_id or "",
            "api_request_id": api_request_id or "",
            "tool_call_id": tool_call_id,
            "tool_name": tool_name or "",
            "tool_status": tool_status or _DEFAULT_TOOL_STATUS,
            "created_at": created_at or utc_now_iso(),
            "raw_sha256": digest,
            "raw_bytes": raw_byte_len(raw_text),
            "raw_text": raw_text,
            "raw_source": raw_source or DEFAULT_RAW_SOURCE,
            "preview_strategy": preview_strategy or "none",
            "preview_bytes": int(preview_bytes or 0),
            "omitted_bytes": int(omitted_bytes or 0),
            "lossy": bool(lossy),
            "classification_reason": classification_reason or "",
            "redaction_applied": bool(redaction_applied),
        }
        if metadata:
            record["metadata"] = dict(metadata)
        for key, value in extra.items():
            if key not in record:
                record[key] = value

        final_path = self.path_for(candidate_id, session_id=session_id)
        self._write_record_and_verify(final_path, record)
        return record

    def write_tombstone(
        self,
        *,
        artifact_id: str,
        session_id: str,
        reason: str,
        deleted_at: str | None = None,
        metadata: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        tombstone = {
            "artifact_id": artifact_id,
            "session_id": session_id,
            "deleted_at": deleted_at or utc_now_iso(),
            "reason": reason,
        }
        if metadata:
            tombstone.update(dict(metadata))
        atomic_write_json_file(
            self.tombstone_path_for(artifact_id, session_id=session_id),
            tombstone,
        )
        return tombstone

    def expand_artifact(
        self,
        artifact_id: str,
        *,
        session_id: str | None = None,
        max_bytes: int | None = None,
        range_start: int | None = None,
        range_end: int | None = None,
    ) -> dict[str, Any]:
        """Return exact raw content or a loud structured error."""

        try:
            record = self.read_record(artifact_id, session_id=session_id)
            raw_text = str(record.get("raw_text", ""))
            content, start, end, byte_count, truncated = _slice_text_by_utf8_bytes(
                raw_text,
                range_start=range_start,
                range_end=range_end,
                max_bytes=max_bytes,
            )
            return {
                "id": artifact_id,
                "ok": True,
                "raw_sha256": record["raw_sha256"],
                "bytes_returned": byte_count,
                "truncated": truncated,
                "range": {"start": start, "end": end},
                "content": content,
            }
        except ArtifactGoneError as exc:
            return {
                "id": artifact_id,
                "ok": False,
                "error": "gone",
                "deleted_at": exc.tombstone.get("deleted_at"),
                "reason": exc.tombstone.get("reason"),
            }
        except ArtifactNotFoundError:
            return {"id": artifact_id, "ok": False, "error": "not_found"}
        except ArtifactIntegrityError as exc:
            return {"id": artifact_id, "ok": False, "error": "hash_mismatch", "message": str(exc)}
        except Exception as exc:
            return {"id": artifact_id, "ok": False, "error": "store_error", "message": str(exc)}

    def _write_record_and_verify(self, final_path: Path, record: Mapping[str, Any]) -> None:
        atomic_write_json_file(final_path, record)
        try:
            verified = self.read_record(record["artifact_id"], session_id=record["session_id"])
        except Exception:
            try:
                final_path.unlink()
                _fsync_dir(final_path.parent)
            except OSError:
                pass
            raise
        if verified.get("raw_sha256") != record.get("raw_sha256"):
            try:
                final_path.unlink()
                _fsync_dir(final_path.parent)
            except OSError:
                pass
            raise ArtifactIntegrityError(
                f"hash mismatch after write for {record.get('artifact_id')}"
            )

    @staticmethod
    def _verify_record(data: Mapping[str, Any], *, expected_artifact_id: str | None = None) -> None:
        if not isinstance(data, Mapping):
            raise ArtifactIntegrityError("artifact JSON is not an object")
        if data.get("schema_version") != SCHEMA_VERSION:
            raise ArtifactIntegrityError(f"unsupported artifact schema: {data.get('schema_version')!r}")
        artifact_id = str(data.get("artifact_id") or "")
        if expected_artifact_id is not None and artifact_id != expected_artifact_id:
            raise ArtifactIntegrityError(
                f"artifact id mismatch: expected {expected_artifact_id!r}, got {artifact_id!r}"
            )
        raw_text = data.get("raw_text")
        if not isinstance(raw_text, str):
            raise ArtifactIntegrityError("artifact raw_text is missing or not a string")
        recorded_hash = str(data.get("raw_sha256") or "")
        actual_hash = sha256_text(raw_text)
        if recorded_hash != actual_hash:
            raise ArtifactIntegrityError(
                f"hash mismatch for {artifact_id}: recorded {recorded_hash}, actual {actual_hash}"
            )
        recorded_bytes = data.get("raw_bytes")
        if recorded_bytes is not None and int(recorded_bytes) != raw_byte_len(raw_text):
            raise ArtifactIntegrityError(
                f"raw byte count mismatch for {artifact_id}: recorded {recorded_bytes}, actual {raw_byte_len(raw_text)}"
            )


def _read_json_dict(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ArtifactIntegrityError(f"invalid artifact JSON at {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ArtifactIntegrityError(f"artifact JSON at {path} is not an object")
    return data


def _slice_text_by_utf8_bytes(
    text: str,
    *,
    range_start: int | None = None,
    range_end: int | None = None,
    max_bytes: int | None = None,
) -> tuple[str, int, int, int, bool]:
    raw = text.encode("utf-8")
    total = len(raw)
    start = max(0, int(range_start or 0))
    end = total if range_end is None else max(start, min(total, int(range_end)))
    if max_bytes is not None:
        max_end = start + max(0, int(max_bytes))
        end = min(end, max_end)
    sliced = raw[start:end]
    while sliced:
        try:
            decoded = sliced.decode("utf-8")
            break
        except UnicodeDecodeError:
            sliced = sliced[:-1]
            end -= 1
    else:
        decoded = ""
        end = start
    byte_count = len(sliced)
    truncated = end < total or start > 0
    return decoded, start, end, byte_count, truncated


_DEFAULT_STORE = ArtifactStore


def write_artifact(**kwargs: Any) -> dict[str, Any]:
    return ArtifactStore().write_artifact(**kwargs)


def read_artifact(artifact_id: str, **kwargs: Any) -> dict[str, Any]:
    return ArtifactStore().read_record(artifact_id, **kwargs)


def expand_artifact(artifact_id: str, **kwargs: Any) -> dict[str, Any]:
    return ArtifactStore().expand_artifact(artifact_id, **kwargs)
